const COOKIE_SECRET = process.env.COOKIE_SECRET;
const TWITTER_CONSUMER_API_KEY = process.env.TWITTER_CONSUMER_API_KEY;
const TWITTER_CONSUMER_API_SECRET_KEY =
  process.env.TWITTER_CONSUMER_API_SECRET_KEY;
