module.exports = {
  COOKIE_SECRET = process.env.COOKIE_SECRET,
  TWITTER_CONSUMER_API_KEY = process.env.TWITTER_CONSUMER_API_KEY,
  TWITTER_CONSUMER_API_SECRET_KEY = process.env.TWITTER_CONSUMER_API_SECRET_KEY,
  MONGO_URI: process.env.MONGO_URI,
  COOKIE_KEY: process.env.COOKIE_KEY,
}